version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    environment:
      - BUILD_ENV=${BUILD_ENV}
    volumes:
      - .:/code
      - node-modules:/code/node_modules
    labels:
      - "traefik.enable=false"
  admin-web:
    image: nginx:latest
    depends_on:
      - app
    networks:
      - default
      - docker_default
    volumes:
      - .:/code
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

volumes:
  node-modules:

networks:
  docker_default:
    external:
      name: docker_default